const MIN_DOT_RADIUS = 0, MAX_DOT_RADIUS = 100;

const MIN_CIRCLE_RADIUS = 1, MAX_CIRCLE_RADIUS = 200;
const MIN_CIRCLE_WIDTH = 1, MAX_CIRCLE_WIDTH = 100;

const MIN_BRANCH_LENGTH = 1, MAX_BRANCH_LENGTH = 200;
const MIN_BRANCH_WIDTH = 1, MAX_BRANCH_WIDTH = 100;
const MIN_BRANCH_ANGLE = 0, MAX_BRANCH_ANGLE = 360;

export {
    MIN_DOT_RADIUS,
    MAX_DOT_RADIUS,
    MIN_CIRCLE_RADIUS,
    MAX_CIRCLE_RADIUS,
    MIN_CIRCLE_WIDTH,
    MAX_CIRCLE_WIDTH,
    MIN_BRANCH_LENGTH,
    MAX_BRANCH_LENGTH,
    MIN_BRANCH_WIDTH,
    MAX_BRANCH_WIDTH,
    MIN_BRANCH_ANGLE,
    MAX_BRANCH_ANGLE,
};
